{{ config( alias='name_of_object_instead_of_mode' ) }}
    SELECT 
CUSTOMERID,
FIRSTNAME,
LASTNAME,
EMAIL,
PHONE,
ADDRESS,
CITY,
STATE,
ZIPCODE,
UPDATED_AT,
CONCAT(FIRSTNAME,' ',LASTNAME) AS CUSTOMERNAME
from SLEEKMART_OMS.L1_LANDING.CUSTOMERS