 select
O.ORDERID,
O.ORDERDATE,
O.CUSTOMERID,
O.EMPLOYEEID,
O.STOREID,
O.STATUS,
O.UPDATED_AT,
O.STATUS_DESC,
COUNT(DISTINCT O.ORDERID) AS ORDERCOUNT,
SUM(OI.TOTAL_PRICE) AS Revenue
from  SLEEKMART_OMS.L1_LANDING.orders_stg O
JOIN  SLEEKMART_OMS.L1_LANDING.orderitems_stg OI 
on O.ORDERID = OI.ORDERID
GROUP BY
O.ORDERID,
O.ORDERDATE,
O.CUSTOMERID,
O.EMPLOYEEID,
O.STOREID,
O.STATUS,
O.UPDATED_AT,
O.STATUS_DESC